<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ApplicationIcon>NullPatch.ico</ApplicationIcon>
		<AssemblyName>NullPatch</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="NullPatch.ico" />
	</ItemGroup>
</Project>